export default {
	TEST: 'TEST',
	SHOW_WELCOME_MESSAGE: 'SHOW_WELCOME_MESSAGE',
	SET_USER_DATA: 'SET_USER_DATA',
	UPDATE_APP: 'UPDATE_APP',
	SET_SPLITTER: 'SET_SPLITTER',
	SET_LEFT_SPLITTER: 'SET_LEFT_SPLITTER',
	UPDATE_TABBAR_INDEX: 'UPDATE_TABBAR_INDEX'
}
