export default {
	SELECT_PROJECT: 'SELECT_PROJECT',
	FETCH_SINGLE_PROJECT: "FETCH_SINGLE_PROJECT",
	CHANGES_SAVED: "CHANGES_SAVED",
	UPDATE_PROJECT: "UPDATE_PROJECT",
  OVERRIDE: "OVERRIDE",
  DELETE_PROJECT: "DELETE_PROJECT",
}
