export default {
	TEST: 'TEST',
	MAIN_SPINNER: 'MAIN_SPINNER',
	SET_USER_DATA: 'SET_USER_DATA',
	SET_GLOBAL_DATA: 'SET_GLOBAL_DATA',
	SET_QUESTION_DATA: 'SET_QUESTION_DATA',
	SET_LANGUAGE: 'SET_LANGUAGE'
}
