export default {
	FETCH_ROOT_FOLDERS: 'FETCH_ROOT_FOLDERS',
	FETCH_FOLDER_CHILDREN: 'FETCH_FOLDER_CHILDREN',
	LEAVE_CURRENT_FOLDER: 'LEAVE_CURRENT_FOLDER',
	SET_BREADCRUMBS: 'SET_BREADCRUMBS',
	SORT_FOLDERS: 'SORT_FOLDERS'
}